# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='Novel_num_of_groups',
            field=models.IntegerField(default=0),
        ),
    ]
