# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0002_novel_novel_num_of_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Novel_Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sen_num', models.IntegerField(default=-1)),
                ('end_sen_num', models.IntegerField(default=-1)),
                ('summary', models.TextField(max_length=2000)),
                ('Novel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_annotation.Novel')),
            ],
        ),
        migrations.RemoveField(
            model_name='novel_sequence',
            name='Novel',
        ),
        migrations.DeleteModel(
            name='Novel_Sequence',
        ),
    ]
