# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0003_auto_20171101_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='cur_group_num',
            field=models.IntegerField(default=0),
        ),
    ]
