# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0004_novel_cur_group_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_novel_sequence',
            name='is_beginning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='Novel_Text',
            field=models.TextField(max_length=100000),
        ),
    ]
