# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0005_auto_20171102_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Block_Summary', models.TextField(max_length=10000)),
                ('Time_Block_Full_Text', models.TextField(max_length=100000)),
                ('Seq_Num', models.IntegerField(default=0)),
            ],
        ),
    ]
