# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0006_time_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_block',
            name='Important_Seq',
            field=models.IntegerField(default=-1),
        ),
    ]
