# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0007_time_block_important_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_block',
            name='Novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_annotation.Novel'),
        ),
    ]
