# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0008_time_block_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='Novel_num_of_time_blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='cur_time_block_num',
            field=models.IntegerField(default=0),
        ),
    ]
