# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0009_auto_20171103_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='Novel_num_of_time_blocks',
            new_name='Novel_num_of_trivial_time_blocks',
        ),
    ]
