# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0010_auto_20171103_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_block',
            name='Important_Seq_group_num',
            field=models.IntegerField(default=-1),
        ),
    ]
