# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0011_time_block_important_seq_group_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Block_Position_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Important_Seq_group_num', models.IntegerField(default=-1)),
                ('vote', models.IntegerField(default=0)),
                ('time_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_annotation.Time_Block')),
            ],
        ),
    ]
