# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0012_time_block_position_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Block_Pairwise_Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('Important_Seq_group_num', models.IntegerField(default=-1)),
                ('_id', models.IntegerField(default=0)),
                ('_next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='time_annotation.Time_Block')),
                ('_prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='time_annotation.Time_Block')),
            ],
        ),
    ]
