# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0013_time_block_pairwise_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_block_pairwise_comparison',
            name='Novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_annotation.Novel'),
        ),
    ]
