# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0014_time_block_pairwise_comparison_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_block_pairwise_comparison',
            name='not_sure',
            field=models.IntegerField(default=0),
        ),
    ]
