# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0015_time_block_pairwise_comparison_not_sure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brute_Time_Block_Pairwise_Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('not_sure', models.IntegerField(default=0)),
                ('_id', models.IntegerField(default=0)),
                ('Novel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_annotation.Novel')),
                ('_next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_brute', to='time_annotation.Time_Block')),
                ('_prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_brute', to='time_annotation.Time_Block')),
            ],
        ),
    ]
