# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0016_brute_time_block_pairwise_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='Summary',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
