# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0021_work_result_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnDef_Work_Result_Putter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.TextField(default='', max_length=1000)),
                ('work_description', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Work_Result_Putter',
            new_name='Def_Work_Result_Putter',
        ),
    ]
