# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0023_work_result_putter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_result_putter',
            name='subject_time_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_result_putter', to='time_annotation.Time_Block'),
        ),
    ]
