# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0025_auto_20171109_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_block_pairwise_comparison',
            old_name='block_a_first',
            new_name='vote_num',
        ),
        migrations.RemoveField(
            model_name='time_block_pairwise_comparison',
            name='block_b_first',
        ),
    ]
