# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_annotation', '0026_auto_20171109_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_block_pairwise_comparison',
            old_name='vote_num',
            new_name='vote_number',
        ),
    ]
